### ISSUE TITLE
Any example apps to look at?

### ISSUE THREAD

**Issue by toranb** [flcdrg/ember-cli-typescript#1]
I'm looking to see how this actually works/looks when used with ember-cli. Do you have an example to show this off today?

**Comment by toranb** [comment]
Also- I noticed this addon isn't available (yet) on npm

https://www.npmjs.com/package/ember-cli-typescript

Any reason why?

**Comment by flcdrg** [comment]
Hi @toranb,
thanks for the interest! I created this a little while a go to see what was possible with Ember CLI.

I haven't done any more work on this as while I'm still using Ember, for the moment I'm not making use of the CLI bits.

I haven't put it up on NPM because (a) I wasn't sure that it was working yet and (b) it didn't really occur to me!

I'd welcome any contributions.

david

**Comment by toranb** [comment]
Understood -any chance you have an app using this in the wild that I could poke at? My team is typescript curious and I'd love to see someone using it w/ ember-cli (the ES6 module syntax is the big unknown at this point -hoping you solved this)

thanks again for the addon (published or not)

**Comment by flcdrg** [comment]
Unfortunately not - the app I am working on is a commercial one.

I'm using Ember in an ASP.NET web application, making use of the ember.d.ts
file (I've been submitting PRs to definitelytyped to update that as I've
gone along). I've configured VS to compile the TypeScript to AMD format,
and am using requirejs to pull everything together. There may be better
ways of doing it, but that seems to work ok for me.

If I get a chance, I might generalise the approach and do a blog post and
probably a git repo example.

**Comment by toranb** [comment]
Fair enough :)

If you ever blog about it in detail be sure to update this issue if you think about it.
